project_id = "wan-memory"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
site_url = "https://www.wanmemory.com"
additional_redirect_urls = ["https://www.wanmemory.com/**", "https://wanmemory.com/**", "http://localhost:3000/**"]

[storage]
enabled = true
file_size_limit = "200MiB"
