-- Release blockers: customer approval, consent evidence, payment gates,
-- first-admin bootstrap, and stale draft expiration.

alter table public.orders
  add column if not exists consented_at timestamptz,
  add column if not exists terms_version text,
  add column if not exists privacy_version text,
  add column if not exists external_ai_consent_at timestamptz,
  add column if not exists ai_notice_version text,
  add column if not exists customer_approved_at timestamptz,
  add column if not exists customer_approved_by uuid references public.profiles(id) on delete set null,
  add column if not exists customer_approved_review_asset_id uuid references public.assets(id) on delete set null,
  add column if not exists draft_expires_at timestamptz;

update public.orders
set draft_expires_at = created_at + interval '7 days'
where status = 'awaiting_materials' and draft_expires_at is null;

drop index if exists public.orders_expired_drafts_idx;
create index orders_expired_drafts_idx
on public.orders(draft_expires_at)
where draft_expires_at is not null and status in ('awaiting_materials', 'cancelled');

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.security_events enable row level security;

drop policy if exists security_events_admin_select on public.security_events;
create policy security_events_admin_select on public.security_events for select to authenticated
using (public.is_admin());

grant select on public.security_events to authenticated;

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  v_trusted_sql boolean;
  v_bootstrap_allowed boolean;
begin
  if new.role is not distinct from old.role then return new; end if;

  v_trusted_sql := session_user in ('postgres', 'supabase_admin');
  v_bootstrap_allowed :=
    old.role = 'customer'
    and new.role = 'admin'
    and v_trusted_sql
    and not exists (select 1 from public.profiles where role = 'admin');

  if not public.is_admin() and not v_trusted_sql then
    raise exception 'role cannot be changed';
  end if;

  insert into public.security_events(actor_id, target_user_id, event_type, payload)
  values (
    auth.uid(),
    new.id,
    'profile_role_changed',
    jsonb_build_object('from', old.role, 'to', new.role, 'bootstrap', v_bootstrap_allowed, 'trusted_sql', v_trusted_sql, 'session_user', session_user)
  );
  return new;
end;
$$;

create or replace function public.bootstrap_first_admin(p_email text)
returns uuid
language plpgsql
security definer set search_path = public
as $$
declare
  v_profile_id uuid;
begin
  if session_user not in ('postgres', 'supabase_admin') then
    raise exception 'bootstrap is available only from a trusted SQL session';
  end if;
  if exists (select 1 from public.profiles where role = 'admin') then
    raise exception 'an admin already exists';
  end if;

  select id into v_profile_id
  from public.profiles
  where lower(email) = lower(trim(p_email))
  limit 1;
  if v_profile_id is null then raise exception 'profile not found; sign up first'; end if;

  update public.profiles set role = 'admin' where id = v_profile_id;
  return v_profile_id;
end;
$$;

revoke all on function public.bootstrap_first_admin(text) from public, anon, authenticated;

create or replace function public.create_memory_order(p_data jsonb)
returns table(order_id uuid, order_number text, quoted_price integer)
language plpgsql
security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_number text;
  v_regular_price integer := 29800;
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if coalesce(trim(p_data ->> 'pet_name'), '') = '' then raise exception 'pet name required'; end if;
  if coalesce(trim(p_data ->> 'breed'), '') = '' then raise exception 'breed required'; end if;
  if coalesce(trim(p_data ->> 'age_text'), '') = '' then raise exception 'age required'; end if;
  if jsonb_typeof(coalesce(p_data -> 'personality', 'null'::jsonb)) <> 'array' then raise exception 'personality required'; end if;
  if jsonb_array_length(p_data -> 'personality') < 1 then raise exception 'personality required'; end if;
  if coalesce(trim(p_data ->> 'favorite_memory'), '') = '' then raise exception 'favorite memory required'; end if;
  if coalesce(trim(p_data ->> 'message_to_pet'), '') = '' then raise exception 'message to pet required'; end if;
  if coalesce(trim(p_data ->> 'style'), '') = '' then raise exception 'style required'; end if;
  if coalesce(trim(p_data ->> 'aspect_ratio'), '') = '' then raise exception 'aspect ratio required'; end if;
  if coalesce(trim(p_data ->> 'bgm'), '') = '' then raise exception 'bgm required'; end if;
  if coalesce(p_data ->> 'consent_accepted', 'false') <> 'true' then raise exception 'terms and privacy consent required'; end if;
  if coalesce(p_data ->> 'external_ai_consent_accepted', 'false') <> 'true' then raise exception 'external AI processing consent required'; end if;
  if p_data ->> 'terms_version' is distinct from '2026-07-21' then raise exception 'current terms version required'; end if;
  if p_data ->> 'privacy_version' is distinct from '2026-07-21' then raise exception 'current privacy version required'; end if;
  if p_data ->> 'ai_notice_version' is distinct from '2026-07-21' then raise exception 'current AI notice version required'; end if;

  v_order_number := 'WM-' || to_char(now(), 'YYYY') || '-' || upper(substr(replace(v_order_id::text, '-', ''), 1, 6));

  insert into public.orders (
    id, user_id, order_number, pet_name, name_kana, breed, age_text,
    purpose, personality, first_meeting, favorite_memory, message_to_pet,
    avoid_notes, style, aspect_ratio, narration, bgm, quoted_price,
    regular_price, campaign_id, status, revision_limit, revision_used,
    consented_at, terms_version, privacy_version, external_ai_consent_at,
    ai_notice_version, draft_expires_at
  ) values (
    v_order_id, v_user_id, v_order_number, trim(p_data ->> 'pet_name'),
    nullif(trim(p_data ->> 'name_kana'), ''), trim(p_data ->> 'breed'),
    trim(p_data ->> 'age_text'), p_data ->> 'purpose', p_data -> 'personality',
    nullif(trim(p_data ->> 'first_meeting'), ''), trim(p_data ->> 'favorite_memory'),
    trim(p_data ->> 'message_to_pet'), nullif(trim(p_data ->> 'avoid_notes'), ''),
    trim(p_data ->> 'style'), trim(p_data ->> 'aspect_ratio'),
    coalesce(nullif(trim(p_data ->> 'narration'), ''), 'ナレーションなし'), trim(p_data ->> 'bgm'),
    v_regular_price, v_regular_price, null, 'awaiting_materials', 2, 0,
    now(), '2026-07-21', '2026-07-21', now(), '2026-07-21', now() + interval '7 days'
  );

  insert into public.order_events (order_id, actor_id, event_type, payload)
  values (
    v_order_id,
    v_user_id,
    'order_draft_created',
    jsonb_build_object(
      'quoted_price', v_regular_price,
      'terms_version', '2026-07-21',
      'privacy_version', '2026-07-21',
      'ai_notice_version', '2026-07-21',
      'external_ai_consent', true
    )
  );

  return query select v_order_id, v_order_number, v_regular_price;
end;
$$;

create or replace function public.save_memory_order_draft(p_order_id uuid, p_data jsonb)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if coalesce(trim(p_data ->> 'pet_name'), '') = '' then raise exception 'pet name required'; end if;
  if coalesce(trim(p_data ->> 'breed'), '') = '' then raise exception 'breed required'; end if;
  if coalesce(trim(p_data ->> 'age_text'), '') = '' then raise exception 'age required'; end if;
  if jsonb_typeof(coalesce(p_data -> 'personality', 'null'::jsonb)) <> 'array' then raise exception 'personality required'; end if;
  if jsonb_array_length(p_data -> 'personality') < 1 then raise exception 'personality required'; end if;
  if coalesce(trim(p_data ->> 'favorite_memory'), '') = '' then raise exception 'favorite memory required'; end if;
  if coalesce(trim(p_data ->> 'message_to_pet'), '') = '' then raise exception 'message to pet required'; end if;
  if coalesce(trim(p_data ->> 'style'), '') = '' then raise exception 'style required'; end if;
  if coalesce(trim(p_data ->> 'aspect_ratio'), '') = '' then raise exception 'aspect ratio required'; end if;
  if coalesce(trim(p_data ->> 'bgm'), '') = '' then raise exception 'bgm required'; end if;
  if coalesce(p_data ->> 'consent_accepted', 'false') <> 'true'
     or coalesce(p_data ->> 'external_ai_consent_accepted', 'false') <> 'true' then
    raise exception 'current consent required';
  end if;
  if p_data ->> 'terms_version' is distinct from '2026-07-21'
     or p_data ->> 'privacy_version' is distinct from '2026-07-21'
     or p_data ->> 'ai_notice_version' is distinct from '2026-07-21' then raise exception 'current policy versions required'; end if;

  update public.orders
  set pet_name = trim(p_data ->> 'pet_name'),
      name_kana = nullif(trim(p_data ->> 'name_kana'), ''),
      breed = trim(p_data ->> 'breed'),
      age_text = trim(p_data ->> 'age_text'),
      purpose = p_data ->> 'purpose',
      personality = p_data -> 'personality',
      first_meeting = nullif(trim(p_data ->> 'first_meeting'), ''),
      favorite_memory = trim(p_data ->> 'favorite_memory'),
      message_to_pet = trim(p_data ->> 'message_to_pet'),
      avoid_notes = nullif(trim(p_data ->> 'avoid_notes'), ''),
      style = trim(p_data ->> 'style'),
      aspect_ratio = trim(p_data ->> 'aspect_ratio'),
      narration = coalesce(nullif(trim(p_data ->> 'narration'), ''), 'ナレーションなし'),
      bgm = trim(p_data ->> 'bgm'),
      consented_at = now(),
      terms_version = '2026-07-21',
      privacy_version = '2026-07-21',
      external_ai_consent_at = now(),
      ai_notice_version = '2026-07-21',
      draft_expires_at = now() + interval '7 days'
  where id = p_order_id and user_id = auth.uid() and status = 'awaiting_materials';
  if not found then raise exception 'draft order not found'; end if;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    'order_draft_updated',
    jsonb_build_object('terms_version', '2026-07-21', 'privacy_version', '2026-07-21', 'ai_notice_version', '2026-07-21')
  );
end;
$$;

create or replace function public.accept_order_consents(
  p_order_id uuid,
  p_terms_version text,
  p_privacy_version text,
  p_ai_notice_version text,
  p_consent_accepted boolean,
  p_external_ai_consent_accepted boolean
)
returns timestamptz
language plpgsql
security definer set search_path = public
as $$
declare
  v_accepted_at timestamptz := now();
begin
  if not p_consent_accepted or not p_external_ai_consent_accepted then raise exception 'both consents are required'; end if;
  if p_terms_version is distinct from '2026-07-21' or p_privacy_version is distinct from '2026-07-21' or p_ai_notice_version is distinct from '2026-07-21' then
    raise exception 'current policy versions required';
  end if;

  update public.orders
  set consented_at = v_accepted_at,
      terms_version = p_terms_version,
      privacy_version = p_privacy_version,
      external_ai_consent_at = v_accepted_at,
      ai_notice_version = p_ai_notice_version
  where id = p_order_id and user_id = auth.uid() and status not in ('cancelled', 'delivered');
  if not found then raise exception 'order not found or consent unavailable'; end if;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    'customer_consents_accepted',
    jsonb_build_object('terms_version', p_terms_version, 'privacy_version', p_privacy_version, 'ai_notice_version', p_ai_notice_version)
  );
  return v_accepted_at;
end;
$$;

create or replace function public.submit_memory_order(p_order_id uuid)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_photo_count integer;
  v_launch_count integer;
  v_price integer;
  v_campaign text;
begin
  select * into v_order
  from public.orders
  where id = p_order_id and user_id = auth.uid()
  for update;

  if not found or v_order.status <> 'awaiting_materials' then raise exception 'order not found or cannot be submitted'; end if;
  if v_order.draft_expires_at is not null and v_order.draft_expires_at <= now() then raise exception 'draft expired'; end if;
  if coalesce(trim(v_order.age_text), '') = '' then raise exception 'age required'; end if;
  if jsonb_typeof(v_order.personality) <> 'array' then raise exception 'personality required'; end if;
  if jsonb_array_length(v_order.personality) < 1 then raise exception 'personality required'; end if;
  if coalesce(trim(v_order.favorite_memory), '') = '' then raise exception 'favorite memory required'; end if;
  if coalesce(trim(v_order.message_to_pet), '') = '' then raise exception 'message to pet required'; end if;
  if v_order.consented_at is null or v_order.external_ai_consent_at is null
     or v_order.terms_version is distinct from '2026-07-21'
     or v_order.privacy_version is distinct from '2026-07-21'
     or v_order.ai_notice_version is distinct from '2026-07-21' then raise exception 'current consent record required'; end if;

  select count(*)::integer into v_photo_count
  from public.assets
  where order_id = p_order_id and user_id = auth.uid() and category = 'source_image';
  if v_photo_count < 5 then raise exception 'at least 5 source images are required'; end if;

  perform pg_advisory_xact_lock(hashtext('wan-memory-launch-monitor-10'));
  select count(*)::integer into v_launch_count
  from public.orders
  where campaign_id = 'launch-monitor-10' and status not in ('awaiting_materials', 'cancelled');

  if v_launch_count < 10 then
    v_price := 24800;
    v_campaign := 'launch-monitor-10';
  else
    v_price := v_order.regular_price;
    v_campaign := null;
  end if;

  update public.orders
  set status = 'materials_submitted', quoted_price = v_price, campaign_id = v_campaign,
      stage_updated_at = now(), draft_expires_at = null
  where id = p_order_id;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    'materials_submitted',
    jsonb_build_object(
      'photo_count', v_photo_count,
      'quoted_price', v_price,
      'campaign_id', v_campaign,
      'consented_at', v_order.consented_at,
      'terms_version', v_order.terms_version,
      'privacy_version', v_order.privacy_version,
      'ai_notice_version', v_order.ai_notice_version
    )
  );
end;
$$;

create or replace function public.request_order_revision(p_order_id uuid, p_category text, p_body text)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_revision_number integer;
begin
  if coalesce(trim(p_body), '') = '' then raise exception 'revision body required'; end if;
  select * into v_order from public.orders where id = p_order_id and user_id = auth.uid() for update;
  if not found or v_order.status <> 'customer_review' then raise exception 'order not found or revision unavailable'; end if;
  if v_order.revision_used >= v_order.revision_limit then raise exception 'revision limit reached'; end if;
  if exists (select 1 from public.revision_requests where order_id = p_order_id and status = 'open') then
    raise exception 'previous revision is still open';
  end if;

  v_revision_number := v_order.revision_used + 1;
  insert into public.revision_requests(order_id, user_id, category, body)
  values (p_order_id, auth.uid(), coalesce(nullif(trim(p_category), ''), 'その他'), trim(p_body));

  update public.orders
  set status = 'revision_requested', revision_used = v_revision_number,
      customer_approved_at = null, customer_approved_by = null,
      customer_approved_review_asset_id = null, stage_updated_at = now()
  where id = p_order_id;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    'revision_requested',
    jsonb_build_object('category', p_category, 'revision_number', v_revision_number, 'revision_limit', v_order.revision_limit)
  );
end;
$$;

create or replace function public.customer_approve_review(p_order_id uuid)
returns timestamptz
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_review_asset_id uuid;
  v_approved_at timestamptz := now();
begin
  select * into v_order
  from public.orders
  where id = p_order_id and user_id = auth.uid()
  for update;

  if not found or v_order.status <> 'customer_review' then raise exception 'review approval unavailable'; end if;
  if v_order.payment_status <> 'paid' then raise exception 'payment must be confirmed before approval'; end if;
  if v_order.consented_at is null or v_order.external_ai_consent_at is null
     or v_order.terms_version is distinct from '2026-07-21'
     or v_order.privacy_version is distinct from '2026-07-21'
     or v_order.ai_notice_version is distinct from '2026-07-21' then raise exception 'current consent record required'; end if;
  if exists (select 1 from public.revision_requests where order_id = p_order_id and status = 'open') then
    raise exception 'open revision must be resolved before approval';
  end if;

  select id into v_review_asset_id
  from public.assets
  where order_id = p_order_id and category = 'review_video'
  order by created_at desc, id desc
  limit 1;
  if v_review_asset_id is null then raise exception 'review video not found'; end if;

  update public.orders
  set status = 'quality_check',
      customer_approved_at = v_approved_at,
      customer_approved_by = auth.uid(),
      customer_approved_review_asset_id = v_review_asset_id,
      stage_updated_at = now()
  where id = p_order_id;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    'customer_review_approved',
    jsonb_build_object('review_asset_id', v_review_asset_id, 'approved_at', v_approved_at)
  );
  return v_approved_at;
end;
$$;

-- Final review can only be entered by the customer's explicit approval RPC.
-- In particular, an administrator cannot skip customer_review -> quality_check.
create or replace function public.is_valid_order_transition(p_from text, p_to text)
returns boolean
language sql
immutable
as $$
  select p_from = p_to or (p_from, p_to) in (
    ('awaiting_materials', 'cancelled'),
    ('materials_submitted', 'reviewing_materials'),
    ('materials_submitted', 'cancelled'),
    ('reviewing_materials', 'cancelled'),
    ('concepts_ready', 'reviewing_materials'),
    ('concepts_ready', 'cancelled'),
    ('concept_selected', 'concepts_ready'),
    ('concept_selected', 'production'),
    ('concept_selected', 'cancelled'),
    ('production', 'concept_selected'),
    ('production', 'cancelled'),
    ('customer_review', 'production'),
    ('customer_review', 'cancelled'),
    ('revision_requested', 'production'),
    ('revision_requested', 'cancelled'),
    ('quality_check', 'production'),
    ('quality_check', 'customer_review'),
    ('quality_check', 'cancelled')
  );
$$;

create or replace function public.admin_update_order(
  p_order_id uuid,
  p_status text,
  p_payment_status text,
  p_due_date date,
  p_admin_notes text
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_before public.orders%rowtype;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  select * into v_before from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if not public.is_valid_order_transition(v_before.status, p_status) then
    raise exception 'invalid order status transition: % -> %', v_before.status, p_status;
  end if;
  if p_payment_status not in ('pending', 'invoice_sent', 'paid', 'refunded') then raise exception 'invalid payment status'; end if;

  if p_status in ('production', 'customer_review', 'revision_requested', 'quality_check') and p_payment_status <> 'paid' then
    raise exception 'payment must be confirmed before production';
  end if;
  if p_status in ('production', 'customer_review', 'revision_requested', 'quality_check')
     and (v_before.consented_at is null or v_before.external_ai_consent_at is null
       or v_before.terms_version is distinct from '2026-07-21'
       or v_before.privacy_version is distinct from '2026-07-21'
       or v_before.ai_notice_version is distinct from '2026-07-21') then
    raise exception 'current consent record required before production';
  end if;
  if p_status = 'quality_check' and exists (
    select 1 from public.revision_requests where order_id = p_order_id and status = 'open'
  ) then raise exception 'open revision must be resolved'; end if;

  update public.orders
  set status = p_status,
      payment_status = p_payment_status,
      due_date = p_due_date,
      admin_notes = nullif(trim(coalesce(p_admin_notes, '')), ''),
      customer_approved_at = case when status = 'quality_check' and p_status <> 'quality_check' then null else customer_approved_at end,
      customer_approved_by = case when status = 'quality_check' and p_status <> 'quality_check' then null else customer_approved_by end,
      customer_approved_review_asset_id = case when status = 'quality_check' and p_status <> 'quality_check' then null else customer_approved_review_asset_id end,
      stage_updated_at = case when status is distinct from p_status then now() else stage_updated_at end
  where id = p_order_id;

  if v_before.status is distinct from p_status
     or v_before.payment_status is distinct from p_payment_status
     or v_before.due_date is distinct from p_due_date
     or v_before.admin_notes is distinct from nullif(trim(coalesce(p_admin_notes, '')), '') then
    insert into public.order_events(order_id, actor_id, event_type, payload)
    values (
      p_order_id,
      auth.uid(),
      'admin_order_updated',
      jsonb_build_object(
        'before', jsonb_build_object('status', v_before.status, 'payment_status', v_before.payment_status, 'due_date', v_before.due_date),
        'after', jsonb_build_object('status', p_status, 'payment_status', p_payment_status, 'due_date', p_due_date),
        'admin_notes_changed', v_before.admin_notes is distinct from nullif(trim(coalesce(p_admin_notes, '')), '')
      )
    );
  end if;
end;
$$;

create or replace function public.admin_register_video_asset(
  p_order_id uuid,
  p_category text,
  p_storage_path text,
  p_original_filename text,
  p_mime_type text,
  p_file_size bigint
)
returns uuid
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_asset_id uuid;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  if p_category not in ('review_video', 'final_video') then raise exception 'invalid video category'; end if;
  if p_mime_type not in ('video/mp4', 'video/quicktime', 'video/webm') then raise exception 'invalid video mime type'; end if;
  if p_file_size <= 0 or p_file_size > 209715200 then raise exception 'invalid video file size'; end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if v_order.payment_status <> 'paid' then raise exception 'payment must be confirmed before video production'; end if;
  if v_order.consented_at is null or v_order.external_ai_consent_at is null
     or v_order.terms_version is distinct from '2026-07-21'
     or v_order.privacy_version is distinct from '2026-07-21'
     or v_order.ai_notice_version is distinct from '2026-07-21' then raise exception 'current consent record required before video production'; end if;
  if p_storage_path not like v_order.user_id::text || '/' || v_order.id::text || '/%' then raise exception 'invalid storage path'; end if;

  if p_category = 'review_video' and v_order.status not in ('production', 'revision_requested', 'customer_review') then
    raise exception 'review video cannot be uploaded in current status';
  end if;
  if p_category = 'final_video' then
    if v_order.status <> 'quality_check' then raise exception 'final video requires quality_check status'; end if;
    if v_order.customer_approved_at is null or v_order.customer_approved_review_asset_id is null then
      raise exception 'customer approval required before final video';
    end if;
    if exists (select 1 from public.revision_requests where order_id = p_order_id and status = 'open') then
      raise exception 'open revision must be resolved before final video';
    end if;
  end if;

  insert into public.assets(order_id, user_id, category, storage_path, original_filename, mime_type, file_size)
  values (p_order_id, v_order.user_id, p_category, p_storage_path, p_original_filename, p_mime_type, p_file_size)
  returning id into v_asset_id;

  if p_category = 'review_video' then
    update public.orders
    set status = 'customer_review',
        customer_approved_at = null,
        customer_approved_by = null,
        customer_approved_review_asset_id = null,
        stage_updated_at = now()
    where id = p_order_id;
  end if;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    case when p_category = 'review_video' then 'review_video_uploaded' else 'final_video_uploaded' end,
    jsonb_build_object('asset_id', v_asset_id, 'filename', p_original_filename, 'file_size', p_file_size)
  );
  return v_asset_id;
end;
$$;

create or replace function public.admin_deliver_order(
  p_order_id uuid,
  p_asset_id uuid,
  p_title text,
  p_customer_message text
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  if coalesce(trim(p_title), '') = '' then raise exception 'delivery title required'; end if;
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if v_order.payment_status <> 'paid' then raise exception 'payment must be confirmed before delivery'; end if;
  if v_order.status <> 'quality_check' then raise exception 'delivery requires quality_check status'; end if;
  if v_order.customer_approved_at is null or v_order.customer_approved_review_asset_id is null then
    raise exception 'customer approval required before delivery';
  end if;
  if exists (select 1 from public.revision_requests where order_id = p_order_id and status = 'open') then
    raise exception 'open revision must be resolved before delivery';
  end if;
  if not exists (
    select 1 from public.assets where id = p_asset_id and order_id = p_order_id and category = 'final_video'
  ) then raise exception 'final video asset not found'; end if;

  insert into public.deliveries(order_id, final_asset_id, title, customer_message, delivered_at)
  values (p_order_id, p_asset_id, trim(p_title), nullif(trim(coalesce(p_customer_message, '')), ''), now())
  on conflict (order_id) do update
  set final_asset_id = excluded.final_asset_id,
      title = excluded.title,
      customer_message = excluded.customer_message,
      delivered_at = now();

  update public.orders set status = 'delivered', stage_updated_at = now() where id = p_order_id;
  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (
    p_order_id,
    auth.uid(),
    'order_delivered',
    jsonb_build_object(
      'asset_id', p_asset_id,
      'title', trim(p_title),
      'customer_approved_at', v_order.customer_approved_at,
      'approved_review_asset_id', v_order.customer_approved_review_asset_id
    )
  );
end;
$$;

create or replace function public.expire_memory_order_draft(p_order_id uuid)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  update public.orders
  set status = 'cancelled', stage_updated_at = now(), campaign_id = null,
      personality = '[]'::jsonb,
      first_meeting = null,
      favorite_memory = null,
      message_to_pet = null,
      avoid_notes = null,
      admin_notes = null,
      selected_concept_slot = null
  where id = p_order_id
    and status = 'awaiting_materials'
    and draft_expires_at is not null
    and draft_expires_at <= now();
  if not found then raise exception 'expired draft not found'; end if;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (p_order_id, null, 'draft_expired', jsonb_build_object('expired_at', now()));
end;
$$;

revoke all on function public.accept_order_consents(uuid, text, text, text, boolean, boolean) from public;
revoke all on function public.customer_approve_review(uuid) from public;
revoke all on function public.expire_memory_order_draft(uuid) from public, anon, authenticated;

grant execute on function public.accept_order_consents(uuid, text, text, text, boolean, boolean) to authenticated;
grant execute on function public.customer_approve_review(uuid) to authenticated;
grant execute on function public.expire_memory_order_draft(uuid) to service_role;
