-- Admin-initiated cancellation and data removal, for when a customer asks to
-- call off an order. Three levels, each stricter than the last:
--
--   1. admin_cancel_order      status -> cancelled with a recorded reason.
--                              Nothing is destroyed.
--   2. admin_purge_order_files cancelled orders only: removes the customer's
--                              photos and videos, but keeps the order row so
--                              order number, price and payment history survive.
--   3. admin_delete_order      cancelled AND never-paid orders only: removes the
--                              order row itself. Orders that ever reached Stripe
--                              keep a record, since payment history has to be
--                              retained.
--
-- The file-removing functions return storage paths; the caller is responsible
-- for deleting those objects from the order-assets bucket. A storage object
-- left behind is recoverable, a prematurely deleted DB row is not, so the row
-- is always removed first and storage cleanup follows.

-- Deleting an order cascades its order_events away with it, so the record of
-- who deleted it has to live somewhere that does not reference orders.
create table if not exists public.deleted_order_log (
  id bigint generated by default as identity primary key,
  order_id uuid not null,
  order_number text not null,
  customer_email text,
  pet_name text,
  quoted_price integer,
  payment_status text,
  reason text not null,
  deleted_file_count integer not null default 0,
  deleted_by uuid references public.profiles(id) on delete set null,
  deleted_at timestamptz not null default now()
);

create index if not exists deleted_order_log_deleted_at_idx
  on public.deleted_order_log(deleted_at desc);

alter table public.deleted_order_log enable row level security;

-- Read-only to admins. Rows are written exclusively by the security definer
-- function below, which bypasses RLS, so no insert policy is granted.
drop policy if exists deleted_order_log_select on public.deleted_order_log;
create policy deleted_order_log_select on public.deleted_order_log for select to authenticated
using (public.is_admin());

create or replace function public.admin_cancel_order(p_order_id uuid, p_reason text)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  if v_reason is null then raise exception 'cancellation reason required'; end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if v_order.status = 'cancelled' then raise exception 'order is already cancelled'; end if;
  if not public.is_valid_order_transition(v_order.status, 'cancelled') then
    raise exception 'this order can no longer be cancelled';
  end if;

  update public.orders
  set status = 'cancelled',
      campaign_id = null,
      draft_expires_at = null,
      stage_updated_at = now()
  where id = p_order_id;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (p_order_id, auth.uid(), 'admin_order_cancelled', jsonb_build_object(
    'reason', v_reason,
    'previous_status', v_order.status,
    'payment_status', v_order.payment_status
  ));
end;
$$;

-- Two foreign keys point at assets with ON DELETE RESTRICT: deliveries.final_asset_id
-- and the assets self-reference source_still_asset_id (render clip -> scene still).
-- RESTRICT is enforced per row rather than at end of statement, so a single bulk
-- delete would fail even though the referencing rows are going away too. Both
-- references are cleared first.
create or replace function public.admin_purge_order_files(p_order_id uuid)
returns setof text
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_paths text[];
begin
  if not public.is_admin() then raise exception 'admin required'; end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if v_order.status <> 'cancelled' then
    raise exception 'cancel the order before deleting its files';
  end if;

  select coalesce(array_agg(storage_path), '{}'::text[])
    into v_paths
    from public.assets
   where order_id = p_order_id;

  delete from public.deliveries where order_id = p_order_id;

  update public.assets
  set source_still_asset_id = null
  where order_id = p_order_id and source_still_asset_id is not null;

  update public.orders
  set stills_approved_asset_ids = null,
      stills_approved_at = null,
      stills_approved_by = null,
      stills_approved_version = null
  where id = p_order_id;

  delete from public.assets where order_id = p_order_id;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (p_order_id, auth.uid(), 'order_files_purged', jsonb_build_object(
    'deleted_file_count', coalesce(array_length(v_paths, 1), 0)
  ));

  return query select unnest(v_paths);
end;
$$;

create or replace function public.admin_delete_order(p_order_id uuid, p_reason text)
returns setof text
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
  v_paths text[];
  v_email text;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  if v_reason is null then raise exception 'deletion reason required'; end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if v_order.status <> 'cancelled' then
    raise exception 'cancel the order before deleting it';
  end if;
  -- Anything that ever reached Stripe keeps its row; payment history is retained.
  if v_order.payment_status <> 'pending' then
    raise exception 'orders with payment history cannot be deleted';
  end if;

  select email into v_email from public.profiles where id = v_order.user_id;

  select coalesce(array_agg(storage_path), '{}'::text[])
    into v_paths
    from public.assets
   where order_id = p_order_id;

  insert into public.deleted_order_log(
    order_id, order_number, customer_email, pet_name, quoted_price,
    payment_status, reason, deleted_file_count, deleted_by
  ) values (
    p_order_id, v_order.order_number, v_email, v_order.pet_name, v_order.quoted_price,
    v_order.payment_status, v_reason, coalesce(array_length(v_paths, 1), 0), auth.uid()
  );

  delete from public.deliveries where order_id = p_order_id;

  update public.assets
  set source_still_asset_id = null
  where order_id = p_order_id and source_still_asset_id is not null;

  delete from public.assets where order_id = p_order_id;
  delete from public.orders where id = p_order_id;

  return query select unnest(v_paths);
end;
$$;

revoke all on function public.admin_cancel_order(uuid, text) from public, anon;
revoke all on function public.admin_purge_order_files(uuid) from public, anon;
revoke all on function public.admin_delete_order(uuid, text) from public, anon;
grant execute on function public.admin_cancel_order(uuid, text) to authenticated;
grant execute on function public.admin_purge_order_files(uuid) to authenticated;
grant execute on function public.admin_delete_order(uuid, text) to authenticated;
