create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_number text not null unique,
  pet_name text not null,
  name_kana text,
  breed text not null,
  age_text text,
  purpose text not null check (purpose in ('いまを残す', '虹の橋メモリアル')),
  personality jsonb not null default '[]'::jsonb,
  first_meeting text,
  favorite_memory text,
  message_to_pet text,
  avoid_notes text,
  style text not null,
  aspect_ratio text not null,
  narration text not null,
  bgm text not null,
  status text not null default 'awaiting_materials' check (status in (
    'awaiting_materials', 'materials_submitted', 'reviewing_materials',
    'concepts_ready', 'concept_selected', 'production', 'customer_review',
    'revision_requested', 'quality_check', 'delivered', 'cancelled'
  )),
  payment_status text not null default 'pending' check (payment_status in ('pending', 'invoice_sent', 'paid', 'refunded')),
  quoted_price integer not null,
  regular_price integer not null default 29800,
  currency text not null default 'JPY',
  campaign_id text,
  selected_concept_slot text check (selected_concept_slot in ('A', 'B')),
  due_date date,
  admin_notes text,
  stage_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists orders_status_idx on public.orders(status, created_at desc);

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  category text not null check (category in ('source_image', 'source_video', 'final_video', 'thumbnail')),
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  file_size bigint not null check (file_size >= 0),
  created_at timestamptz not null default now()
);

create index if not exists assets_order_idx on public.assets(order_id, created_at);

create table if not exists public.concepts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  slot text not null check (slot in ('A', 'B')),
  title text not null,
  tone text not null,
  summary text not null,
  scenes jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id, slot)
);

create table if not exists public.revision_requests (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  category text not null,
  body text not null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists revision_requests_order_idx on public.revision_requests(order_id, created_at desc);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 3000),
  created_at timestamptz not null default now()
);

create index if not exists messages_order_idx on public.messages(order_id, created_at);

create table if not exists public.deliveries (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  final_asset_id uuid not null references public.assets(id) on delete restrict,
  title text not null,
  customer_message text,
  delivered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists concepts_set_updated_at on public.concepts;
create trigger concepts_set_updated_at before update on public.concepts
for each row execute function public.set_updated_at();

drop trigger if exists deliveries_set_updated_at on public.deliveries;
create trigger deliveries_set_updated_at before update on public.deliveries
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, nullif(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, full_name)
select id, email, nullif(raw_user_meta_data ->> 'full_name', '')
from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.role is distinct from old.role and not public.is_admin() then
    raise exception 'role cannot be changed';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role before update on public.profiles
for each row execute function public.protect_profile_role();

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.assets enable row level security;
alter table public.concepts enable row level security;
alter table public.revision_requests enable row level security;
alter table public.messages enable row level security;
alter table public.deliveries enable row level security;
alter table public.order_events enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists orders_select on public.orders;
create policy orders_select on public.orders for select to authenticated
using (user_id = auth.uid() or public.is_admin());
drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update on public.orders for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists assets_select on public.assets;
create policy assets_select on public.assets for select to authenticated
using (user_id = auth.uid() or public.is_admin());
drop policy if exists assets_insert on public.assets;
create policy assets_insert on public.assets for insert to authenticated
with check (
  public.is_admin() or (
    user_id = auth.uid() and exists (
      select 1 from public.orders where id = order_id and user_id = auth.uid()
    )
  )
);
drop policy if exists assets_delete_own_source on public.assets;
create policy assets_delete_own_source on public.assets for delete to authenticated
using ((user_id = auth.uid() and category in ('source_image', 'source_video')) or public.is_admin());

drop policy if exists concepts_select on public.concepts;
create policy concepts_select on public.concepts for select to authenticated
using (
  public.is_admin() or (
    status = 'published' and exists (
      select 1 from public.orders where id = order_id and user_id = auth.uid()
    )
  )
);
drop policy if exists concepts_admin_all on public.concepts;
create policy concepts_admin_all on public.concepts for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists revisions_select on public.revision_requests;
create policy revisions_select on public.revision_requests for select to authenticated
using (user_id = auth.uid() or public.is_admin());
drop policy if exists revisions_insert on public.revision_requests;
create policy revisions_insert on public.revision_requests for insert to authenticated
with check (
  user_id = auth.uid() and exists (
    select 1 from public.orders where id = order_id and user_id = auth.uid()
  )
);
drop policy if exists revisions_admin_update on public.revision_requests;
create policy revisions_admin_update on public.revision_requests for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select to authenticated
using (
  public.is_admin() or exists (
    select 1 from public.orders where id = order_id and user_id = auth.uid()
  )
);
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated
with check (
  sender_id = auth.uid() and (
    public.is_admin() or exists (
      select 1 from public.orders where id = order_id and user_id = auth.uid()
    )
  )
);

drop policy if exists deliveries_select on public.deliveries;
create policy deliveries_select on public.deliveries for select to authenticated
using (
  public.is_admin() or exists (
    select 1 from public.orders where id = order_id and user_id = auth.uid()
  )
);
drop policy if exists deliveries_admin_all on public.deliveries;
create policy deliveries_admin_all on public.deliveries for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists order_events_select on public.order_events;
create policy order_events_select on public.order_events for select to authenticated
using (
  public.is_admin() or exists (
    select 1 from public.orders where id = order_id and user_id = auth.uid()
  )
);
drop policy if exists order_events_admin_insert on public.order_events;
create policy order_events_admin_insert on public.order_events for insert to authenticated
with check (public.is_admin());

create or replace function public.create_memory_order(p_data jsonb)
returns table(order_id uuid, order_number text, quoted_price integer)
language plpgsql
security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_number text;
  v_quoted_price integer;
  v_campaign_id text;
  v_launch_count integer;
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if coalesce(trim(p_data ->> 'pet_name'), '') = '' then raise exception 'pet name required'; end if;
  if coalesce(trim(p_data ->> 'breed'), '') = '' then raise exception 'breed required'; end if;

  perform pg_advisory_xact_lock(hashtext('wan-memory-launch-monitor-10'));
  select count(*) into v_launch_count
  from public.orders
  where campaign_id = 'launch-monitor-10' and status <> 'cancelled';

  if v_launch_count < 10 then
    v_quoted_price := 24800;
    v_campaign_id := 'launch-monitor-10';
  else
    v_quoted_price := 29800;
    v_campaign_id := null;
  end if;

  v_order_number := 'WM-' || to_char(now(), 'YYYY') || '-' || upper(substr(replace(v_order_id::text, '-', ''), 1, 6));

  insert into public.orders (
    id, user_id, order_number, pet_name, name_kana, breed, age_text,
    purpose, personality, first_meeting, favorite_memory, message_to_pet,
    avoid_notes, style, aspect_ratio, narration, bgm, quoted_price,
    regular_price, campaign_id, status
  ) values (
    v_order_id, v_user_id, v_order_number, trim(p_data ->> 'pet_name'),
    nullif(trim(p_data ->> 'name_kana'), ''), trim(p_data ->> 'breed'),
    nullif(trim(p_data ->> 'age_text'), ''), p_data ->> 'purpose',
    coalesce(p_data -> 'personality', '[]'::jsonb),
    nullif(trim(p_data ->> 'first_meeting'), ''),
    nullif(trim(p_data ->> 'favorite_memory'), ''),
    nullif(trim(p_data ->> 'message_to_pet'), ''),
    nullif(trim(p_data ->> 'avoid_notes'), ''),
    p_data ->> 'style', p_data ->> 'aspect_ratio', p_data ->> 'narration',
    p_data ->> 'bgm', v_quoted_price, 29800, v_campaign_id, 'awaiting_materials'
  );

  insert into public.order_events (order_id, actor_id, event_type, payload)
  values (v_order_id, v_user_id, 'order_created', jsonb_build_object('quoted_price', v_quoted_price));

  return query select v_order_id, v_order_number, v_quoted_price;
end;
$$;

revoke all on function public.create_memory_order(jsonb) from public;
grant execute on function public.create_memory_order(jsonb) to authenticated;

create or replace function public.get_memory_film_pricing()
returns table(
  current_price integer,
  regular_price integer,
  launch_limit integer,
  launch_used integer,
  launch_remaining integer,
  campaign_active boolean
)
language sql
stable
security definer set search_path = public
as $$
  with counts as (
    select count(*)::integer as used
    from public.orders
    where campaign_id = 'launch-monitor-10' and status <> 'cancelled'
  )
  select
    case when used < 10 then 24800 else 29800 end,
    29800,
    10,
    used,
    greatest(10 - used, 0),
    used < 10
  from counts;
$$;

revoke all on function public.get_memory_film_pricing() from public;
grant execute on function public.get_memory_film_pricing() to anon, authenticated;

create or replace function public.submit_memory_order(p_order_id uuid)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  update public.orders
  set status = 'materials_submitted', stage_updated_at = now()
  where id = p_order_id and user_id = auth.uid() and status = 'awaiting_materials';
  if not found then raise exception 'order not found or cannot be submitted'; end if;
  insert into public.order_events(order_id, actor_id, event_type)
  values (p_order_id, auth.uid(), 'materials_submitted');
end;
$$;

revoke all on function public.submit_memory_order(uuid) from public;
grant execute on function public.submit_memory_order(uuid) to authenticated;

create or replace function public.select_memory_concept(p_order_id uuid, p_slot text)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if p_slot not in ('A', 'B') then raise exception 'invalid concept slot'; end if;
  if not exists (
    select 1 from public.concepts
    where order_id = p_order_id and slot = p_slot and status = 'published'
  ) then raise exception 'concept not available'; end if;

  update public.orders
  set selected_concept_slot = p_slot, status = 'concept_selected', stage_updated_at = now()
  where id = p_order_id and user_id = auth.uid() and status in ('concepts_ready', 'concept_selected');
  if not found then raise exception 'order not found or concept cannot be selected'; end if;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (p_order_id, auth.uid(), 'concept_selected', jsonb_build_object('slot', p_slot));
end;
$$;

revoke all on function public.select_memory_concept(uuid, text) from public;
grant execute on function public.select_memory_concept(uuid, text) to authenticated;

create or replace function public.request_order_revision(p_order_id uuid, p_category text, p_body text)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if coalesce(trim(p_body), '') = '' then raise exception 'revision body required'; end if;
  if not exists (
    select 1 from public.orders
    where id = p_order_id and user_id = auth.uid() and status in ('customer_review', 'delivered')
  ) then raise exception 'order not found or revision unavailable'; end if;

  insert into public.revision_requests(order_id, user_id, category, body)
  values (p_order_id, auth.uid(), coalesce(nullif(trim(p_category), ''), 'その他'), trim(p_body));

  update public.orders
  set status = 'revision_requested', stage_updated_at = now()
  where id = p_order_id;

  insert into public.order_events(order_id, actor_id, event_type, payload)
  values (p_order_id, auth.uid(), 'revision_requested', jsonb_build_object('category', p_category));
end;
$$;

revoke all on function public.request_order_revision(uuid, text, text) from public;
grant execute on function public.request_order_revision(uuid, text, text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'order-assets', 'order-assets', false, 209715200,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'video/mp4', 'video/webm', 'video/quicktime']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists order_assets_select on storage.objects;
create policy order_assets_select on storage.objects for select to authenticated
using (
  bucket_id = 'order-assets' and (
    (storage.foldername(name))[1] = auth.uid()::text or public.is_admin()
  )
);

drop policy if exists order_assets_insert on storage.objects;
create policy order_assets_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'order-assets' and (
    (storage.foldername(name))[1] = auth.uid()::text or public.is_admin()
  )
);

drop policy if exists order_assets_delete on storage.objects;
create policy order_assets_delete on storage.objects for delete to authenticated
using (
  bucket_id = 'order-assets' and (
    public.is_admin() or (
      (storage.foldername(name))[1] = auth.uid()::text and exists (
        select 1 from public.assets
        where storage_path = name and user_id = auth.uid() and category in ('source_image', 'source_video')
      )
    )
  )
);

grant select, update on public.profiles to authenticated;
grant select on public.orders to authenticated;
grant select, insert, delete on public.assets to authenticated;
grant select, insert, update, delete on public.concepts to authenticated;
grant select, insert, update on public.revision_requests to authenticated;
grant select, insert on public.messages to authenticated;
grant select, insert, update, delete on public.deliveries to authenticated;
grant select, insert on public.order_events to authenticated;

-- 管理者にするユーザーは、初回登録後にSQL Editorで次を実行します。
-- update public.profiles set role = 'admin' where email = 'owner@example.com';
